<?php
/*	Poodle WCMS, Copyright (c) MH X Solutions since 2010. All rights reserved.

	The contents of this file are subject to the terms of the
	Common Development and Distribution License, Version 1.0 only
	(the "License").  You may not use this file except in compliance
	with the License.
*/

$to_latin = array(
	# Greek
	'α'=>'a','β'=>'b','γ'=>'y','δ'=>'d','ε'=>'e','ζ'=>'z','η'=>'i','θ'=>'th',
	'ι'=>'i','κ'=>'k','λ'=>'l','μ'=>'m','ν'=>'n','ξ'=>'ks','ο'=>'o','π'=>'p',
	'ρ'=>'r','ς'=>'s','σ'=>'s','τ'=>'t','υ'=>'y','φ'=>'f','χ'=>'h','ψ'=>'ps',
	'ω'=>'o',

	# Russian cyrillic
	'а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d','е'=>'e','ё'=>'jo','ж'=>'zh',
	'з'=>'z','и'=>'i','й'=>'j','к'=>'k','л'=>'l','м'=>'m','н'=>'n','о'=>'o',
	'п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u','ф'=>'f','х'=>'x','ц'=>'c',
	'ч'=>'ch','ш'=>'sh','щ'=>'th','ъ'=>'qh','ы'=>'y','ь'=>'q','э'=>'eh',
	'ю'=>'ju','я'=>'ja',

	# Ukrainian cyrillic
	'ґ'=>'gh','є'=>'je','і'=>'i','ї'=>'ji',

	# Georgian
	'ა'=>'a','ბ'=>'b','გ'=>'g','დ'=>'d','ე'=>'e','ვ'=>'v','ზ'=>'z','თ'=>'th',
	'ი'=>'i','კ'=>'p','ლ'=>'l','მ'=>'m','ნ'=>'n','ო'=>'o','პ'=>'p','ჟ'=>'zh',
	'რ'=>'r','ს'=>'s','ტ'=>'t','უ'=>'u','ფ'=>'ph','ქ'=>'kh','ღ'=>'gh','ყ'=>'q',
	'შ'=>'sh','ჩ'=>'ch','ც'=>'c','ძ'=>'dh','წ'=>'w','ჭ'=>'j','ხ'=>'x','ჯ'=>'jh',
	'ჰ'=>'xh',
);
