<?php

// NOTE: required attributes must come first
// https://www.w3.org/TR/MathML3/

$DTD = array_merge($DTD, array(

	'DOCTYPE'    => '<!DOCTYPE math PUBLIC "-//W3C//DTD MathML 3.0//EN" "http://www.w3.org/Math/DTD/mathml3/mathml3.dtd">',
	'EMPTY-TAGS' => array('abs','and','approx','arccos','arccosh','arccot','arccoth','arccsc','arccsch','arcsec','arcsech','arcsin','arcsinh','arctan','arctanh','arg','card','cartesianproduct','ceiling','codomain','complexes','compose','conjugate','cos','cosh','cot','coth','csc','csch','curl','determinant','diff','divergence','divide','domain','emptyset','eq','equivalent','eulergamma','exists','exp','exponentiale','factorial','factorof','false','floor','forall','gcd','geq','grad','gt','ident','image','imaginary','imaginaryi','implies','in','infinity','int','integers','intersect','laplacian','lcm','leq','limit','ln','log','lt','maligngroup','malignmark','max','mean','median','mglyph','min','minus','mode','moment','mprescripts','msline','mspace','naturalnumbers','neq','none','not','notanumber','notin','notprsubset','notsubset','or','outerproduct','partialdiff','pi','plus','power','primes','product','prsubset','quotient','rationals','real','reals','rem','root','scalarproduct','sdev','sec','sech','selector','sep','setdiff','sin','sinh','subset','sum','tan','tanh','tendsto','times','transpose','true','union','variance','vectorproduct','xor'),

	'XML'        => true,

	'STANDARD_ATTRIBUTES' => array('class'=>0, 'href'=>0, 'id'=>0, 'style'=>0, 'xref'=>0,
		// DefEncAtt not on all in Strict but in most in Full
		'definitionURL'=>0, 'encoding'=>0,
		// Mathematics style attributes common to presentation elements
		'mathbackground'=>0, 'mathcolor'=>0,
		// Mathematics style attributes common to token elements
		'mathvariant'=>0, 'mathsize'=>0, 'dir'=>0,
	),

	'abs'                 => array(),
	'and'                 => array(),
	'annotation'          => array('cd'=>0, 'name'=>0, 'src'=>0),
	'annotation-xml'      => array('cd'=>0, 'name'=>0, 'src'=>0),
	'apply'               => array(),
	'approx'              => array(),
	'arccos'              => array(),
	'arccosh'             => array(),
	'arccot'              => array(),
	'arccoth'             => array(),
	'arccsc'              => array(),
	'arccsch'             => array(),
	'arcsec'              => array(),
	'arcsech'             => array(),
	'arcsin'              => array(),
	'arcsinh'             => array(),
	'arctan'              => array(),
	'arctanh'             => array(),
	'arg'                 => array(),
	'bind'                => array(),
	'bvar'                => array(),
	'card'                => array(),
	'cartesianproduct'    => array(),
	'cbytes'              => array(),
	'ceiling'             => array(),
	'cerror'              => array(),
	'ci'                  => array(),
	'cn'                  => array(),
	'codomain'            => array(),
	'complexes'           => array(),
	'compose'             => array(),
	'condition'           => array(),
	'conjugate'           => array(),
	'cos'                 => array(),
	'cosh'                => array(),
	'cot'                 => array(),
	'coth'                => array(),
	'cs'                  => array(),
	'csc'                 => array(),
	'csch'                => array(),
	'csymbol'             => array('cd'=>0),
	'curl'                => array(),
	'declare'             => array('type'=>0, 'scope'=>0, 'nargs'=>0, 'occurrence'=>0),
	'degree'              => array(),
	'determinant'         => array(),
	'diff'                => array(),
	'divergence'          => array(),
	'divide'              => array(),
	'domain'              => array(),
	'domainofapplication' => array(),
	'emptyset'            => array(),
	'eq'                  => array(),
	'equivalent'          => array(),
	'eulergamma'          => array(),
	'exists'              => array(),
	'exp'                 => array(),
	'exponentiale'        => array(),
	'factorial'           => array(),
	'factorof'            => array(),
	'false'               => array(),
	'floor'               => array(),
	'fn'                  => array(),
	'forall'              => array(),
	'gcd'                 => array(),
	'geq'                 => array(),
	'grad'                => array(),
	'gt'                  => array(),
	'ident'               => array(),
	'image'               => array(),
	'imaginary'           => array(),
	'imaginaryi'          => array(),
	'implies'             => array(),
	'in'                  => array(),
	'infinity'            => array(),
	'int'                 => array(),
	'integers'            => array(),
	'intersect'           => array(),
	'interval'            => array('closure'=>0),
	'inverse'             => array(),
	'lambda'              => array(),
	'laplacian'           => array(),
	'lcm'                 => array(),
	'leq'                 => array(),
	'limit'               => array(),
	'list'                => array('order'=>0),
	'ln'                  => array(),
	'log'                 => array(),
	'logbase'             => array(),
	'lowlimit'            => array(),
	'lt'                  => array(),
	'maction'             => array('actiontype'=>0, 'selection'=>0),
	'maligngroup'         => array('groupalign'=>0),
	'malignmark'          => array('edge'=>0),
	'math'                => array('xmlns'=>'http://www.w3.org/1998/Math/MathML', 'display'=>0, 'specifies'=>0, 'maxwidth'=>0, 'specifies'=>0, 'overflow'=>0, 'specifies'=>0, 'altimg'=>0, 'provides'=>0, 'altimg-width'=>0, 'specifies'=>0, 'altimg-height'=>0, 'specifies'=>0, 'altimg-valign'=>0, 'specifies'=>0, 'alttext'=>0, 'provides'=>0, 'cdgroup'=>0),
	'matrix'              => array(),
	'matrixrow'           => array(),
	'max'                 => array(),
	'mean'                => array(),
	'median'              => array(),
	'menclose'            => array('notation'=>0),
	'merror'              => array(),
	'mfenced'             => array('close'=>0, 'open'=>0, 'separators'=>0),
	'mfrac'               => array('bevelled'=>0, 'denomalign'=>0, 'linethickness'=>0, 'numalign'=>0),
	'mglyph'              => array('alt'=>0, 'height'=>0, 'src'=>0, 'valign'=>0, 'width'=>0),
	'mi'                  => array(),
	'min'                 => array(),
	'minus'               => array(),
	'mlabeledtr'          => array('columnalign'=>0, 'groupalign'=>0, 'rowalign'=>0),
	'mlongdiv'            => array('longdivstyle'=>0),
	'mmultiscripts'       => array('subscriptshift'=>0, 'superscriptshift'=>0),
	'mn'                  => array(),
	'mo'                  => array('accent'=>0, 'fence'=>0, 'form'=>0, 'largeop'=>0, 'lspace'=>0, 'maxsize'=>0, 'minsize'=>0, 'movablelimits'=>0, 'rspace'=>0, 'separator'=>0, 'stretchy'=>0, 'symmetric'=>0),
	'mode'                => array(),
	'moment'              => array(),
	'momentabout'         => array(),
	'mover'               => array('accent'=>0, 'align'=>0),
	'mpadded'             => array('depth'=>0, 'height'=>0, 'lspace'=>0, 'voffset'=>0, 'width'=>0),
	'mphantom'            => array(),
	'mprescripts'         => array('subscriptshift'=>0, 'superscriptshift'=>0),
	'mroot'               => array(),
	'mrow'                => array(),
	'ms'                  => array('lquote'=>0, 'rquote'=>0),
	'mscarries'           => array('crossout'=>0, 'location'=>0, 'position'=>0, 'scriptsizemultiplier'=>0),
	'mscarry'             => array('crossout'=>0, 'location'=>0),
	'msgroup'             => array('position'=>0, 'shift'=>0),
	'msline'              => array('leftoverhang'=>0, 'length'=>0, 'mslinethickness'=>0, 'position'=>0, 'rightoverhang'=>0),
	'mspace'              => array('depth'=>0, 'height'=>0, 'linebreak'=>0, 'width'=>0),
	'msqrt'               => array(),
	'msrow'               => array('position'=>0),
	'mstack'              => array('align'=>0, 'charalign'=>0, 'charspacing'=>0, 'stackalign'=>0),
	'mstyle'              => array('decimalpoint'=>0, 'displaystyle'=>0, 'infixlinebreakstyle'=>0, 'scriptlevel'=>0, 'scriptminsize'=>0, 'scriptsizemultiplier'=>0),
	'msub'                => array('subscriptshift'=>0),
	'msubsup'             => array('subscriptshift'=>0, 'superscriptshift'=>0),
	'msup'                => array('superscriptshift'=>0),
	'mtable'              => array('align'=>0, 'alignmentscope'=>0, 'columnalign'=>0, 'columnlines'=>0, 'columnspacing'=>0, 'columnwidth'=>0, 'displaystyle'=>0, 'equalcolumns'=>0, 'equalrows'=>0, 'frame'=>0, 'framespacing'=>0, 'groupalign'=>0, 'minlabelspacing'=>0, 'rowalign'=>0, 'rowlines'=>0, 'rowspacing'=>0, 'side'=>0, 'width'=>0),
	'mtd'                 => array('columnalign'=>0, 'columnspan'=>0, 'groupalign'=>0, 'rowalign'=>0, 'rowspan'=>0),
	'mtext'               => array(),
	'mtr'                 => array('columnalign'=>0, 'groupalign'=>0, 'rowalign'=>0),
	'munder'              => array('accentunder'=>0, 'align'=>0),
	'munderover'          => array('accent'=>0, 'accentunder'=>0, 'align'=>0),
	'naturalnumbers'      => array(),
	'neq'                 => array(),
	'none'                => array('subscriptshift'=>0, 'superscriptshift'=>0),
	'not'                 => array(),
	'notanumber'          => array(),
	'notin'               => array(),
	'notprsubset'         => array(),
	'notsubset'           => array(),
	'or'                  => array(),
	'otherwise'           => array(),
	'outerproduct'        => array(),
	'partialdiff'         => array(),
	'pi'                  => array(),
	'piece'               => array(),
	'piecewise'           => array(),
	'plus'                => array(),
	'power'               => array(),
	'primes'              => array(),
	'product'             => array(),
	'prsubset'            => array(),
	'quotient'            => array(),
	'rationals'           => array(),
	'real'                => array(),
	'reals'               => array(),
	'reln'                => array(),
	'rem'                 => array(),
	'root'                => array(),
	'scalarproduct'       => array(),
	'sdev'                => array(),
	'sec'                 => array(),
	'sech'                => array(),
	'selector'            => array(),
	'semantics'           => array(),
	'sep'                 => array(),
	'set'                 => array('type'=>0),
	'setdiff'             => array(),
	'share'               => array(),
	'sin'                 => array(),
	'sinh'                => array(),
	'span'                => array(),
	'subset'              => array(),
	'sum'                 => array(),
	'tan'                 => array(),
	'tanh'                => array(),
	'tendsto'             => array('type'=>0),
	'times'               => array(),
	'transpose'           => array(),
	'true'                => array(),
	'union'               => array(),
	'uplimit'             => array(),
	'variance'            => array(),
	'vector'              => array(),
	'vectorproduct'       => array(),
	'xor'                 => array(),

));
